name: changes_info
on: [ pull_request ]

jobs:
  changes_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: sudo apt-get install libyaml-dev
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml git+https://github.com/TwitchPlaysPokemon/pokecat.git
      - id: files
        uses: mmagician/get-changed-files@v2
        with:
          format: 'json'
      - env:
          CHANGED_FILES_JSON: ${{ steps.files.outputs.added_modified }}
        run: |
          echo -e "Stats:\n" > _sets_comments.md
          echo "| file | set | species | hp | atk | def | spe | spA | spD |" >> _sets_comments.md
          echo "| --- | --- | --- | --- | --- | --- | --- | --- | --- |" >> _sets_comments.md
          jq -rc '.[]' <<<"$CHANGED_FILES_JSON" | while read changed_file; do
            file_count=$(find pokesets/ -name "$changed_file" | wc -l)
            if [[ $changed_file == pokesets/* && ( $changed_file == *.yaml || $changed_file == *.yml ) ]]; then
              echo "$changed_file is a pokeset"
              touch _any_changed.markerfile
              python -m pokecat populate "${changed_file}" "${changed_file}.populated"
              python -m pokecat instantiate "${changed_file}.populated" "${changed_file}.instantiated"
              cat "${changed_file}.instantiated" | jq --raw-output ".[] | \"| ${changed_file} | \(.setname) | \(.species.name) | \(.stats.hp) | \(.stats.atk) | \(.stats.def) | \(.stats.spe) | \(.stats.spA) | \(.stats.spD) |\"" >> _sets_comments.md
              cat _sets_comments.md
            else
              echo "$changed_file is not a pokeset"
            fi
          done
          if [[ ! -f _any_changed.markerfile ]]; then
            echo "No sets changed"
            rm _sets_comments.md
          else
            echo "Sets changed. Here's the full output:"
            cat _sets_comments.md
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: Stats
          path: _sets_comments.md
